### ISSUE TITLE
Crash when executing main logic of my Python program

### ISSUE THREAD

**Issue by Saijin-Naib** [crleblanc/PyIrToy#3]
I know you're moved on from PyIrToy, but I'm curious if you could help me understand what this crash could mean:

Traceback (most recent call last):
  File "STL_simple.py", line 466, in <module>
    pIRT = pIRt.IrToy(serialDevice)
  File "/usr/local/lib/python3.5/dist-packages/irtoy_nohs.py", line 48, in __init__
    hardware, revision = self.firmware_revision()
  File "/usr/local/lib/python3.5/dist-packages/irtoy_nohs.py", line 66, in firmware_revision
    hardwareVersion = int(versionString[1:2])
ValueError: invalid literal for int() with base 10: b'\xff'

**Comment by crleblanc** [comment]
It looks like it failing to parse the version information from the IR toy.  I haven't used this device in a long time so can't offer much help.  My guess is once it starts misbehaving it will return garbage information for almost any command, including the version information.

I see there's only one post on the IR Toy forum for 2019 with no replies.  That's about as dead as the parrot in the old Monty Python skit.
